package golfrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import golfrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.13 16:17:21 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi89 */
  @Test
  public void testGetNimi89() {    // Pelaaja: 89
    Pelaaja a = new Pelaaja(); 
    a.taytaPeluri(); 
    assertEquals("From: Pelaaja line: 92", "Rory McIlroy", a.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi181 */
  @Test
  public void testRekisteroi181() {    // Pelaaja: 181
    Pelaaja peluri3 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 183", 0, peluri3.getTunnusNro()); 
    peluri3.rekisteroi(); 
    Pelaaja peluri4 = new Pelaaja(); 
    peluri4.rekisteroi(); 
    int i = peluri3.getTunnusNro(); 
    int i2 = peluri4.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 189", i2 - 1, i); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse251 */
  @Test
  public void testParse251() {    // Pelaaja: 251
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse(" 1 | Niko Koo | 22"); 
    assertEquals("From: Pelaaja line: 254", 1, pelaaja.getTunnusNro()); 
  } // Generated by ComTest END
}