package golfrekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import golfrekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.13 16:20:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TilastoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi63 */
  @Test
  public void testRekisteroi63() {    // Tilasto: 63
    Tilasto tilasto = new Tilasto(); 
    assertEquals("From: Tilasto line: 65", 0, tilasto.getTunnusNro()); 
    tilasto.rekisteroi(); 
    Tilasto tilasto2 = new Tilasto(); 
    tilasto2.rekisteroi(); 
    int n1 = tilasto.getTunnusNro(); 
    int n2 = tilasto2.getTunnusNro(); 
    assertEquals("From: Tilasto line: 71", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse106 */
  @Test
  public void testParse106() {    // Tilasto: 106
    Tilasto t = new Tilasto(); 
    t.parse(" 1 | 1 | Driving distance"); 
    assertEquals("From: Tilasto line: 109", 1, t.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro133 */
  @Test
  public void testGetTunnusNro133() {    // Tilasto: 133
    Tilasto a = new Tilasto(); 
    assertEquals("From: Tilasto line: 135", 0, a.getTunnusNro()); 
  } // Generated by ComTest END
}